using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FrogDisplayRotation : MonoBehaviour
{
    public Sprite green, orange, purple, red, white, evil;                                  // declaring public sprites that can have images assigned to them within unity
    public int rotationInt = 0;                                                             // declaring and assigning an int variable before it begins being used

    void Update()
    {
        if (GameObject.Find("Menu Selection").transform.position.y == -0.25)                // searches for "Menu Selection" gameobject and checks if it is in the right Y position for the following statements
        {
            if (rotationInt == 5 && Input.GetKeyDown(KeyCode.A))                            // if player presses "A" when "rotationInt equals 5...
            {
                rotationInt = 4;                                                            // assign "rotationInt" a new number in the negative direction...
                GetComponent<SpriteRenderer>().sprite = white;                              // assign "white" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "white");                                   // and set the "colour" playerpref to "white" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 0 && Input.GetKeyDown(KeyCode.A))                       // if player presses "A" when "rotationInt equals 0...
            {
                rotationInt = 5;                                                            // assign "rotationInt" a new number in the negative direction...
                GetComponent<SpriteRenderer>().sprite = evil;                               // assign "evil" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "evil");                                    // and set the "colour" playerpref to "evil" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 1 && Input.GetKeyDown(KeyCode.A))                       // if player presses "A" when "rotationInt equals 1...
            {
                rotationInt = 0;                                                            // assign "rotationInt" a new number in the negative direction...
                GetComponent<SpriteRenderer>().sprite = green;                              // assign "green" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "green");                                   // and set the "colour" playerpref to "green" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 2 && Input.GetKeyDown(KeyCode.A))                       // if player presses "A" when "rotationInt equals 2...
            {
                rotationInt = 1;                                                            // assign "rotationInt" a new number in the negative direction...
                GetComponent<SpriteRenderer>().sprite = orange;                             // assign "orange" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "orange");                                  // and set the "colour" playerpref to "orange" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 3 && Input.GetKeyDown(KeyCode.A))                       // if player presses "A" when "rotationInt equals 3...
            {
                rotationInt = 2;                                                            // assign "rotationInt" a new number in the negative direction...
                GetComponent<SpriteRenderer>().sprite = purple;                             // assign "purple" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "purple");                                  // and set the "colour" playerpref to "purple" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 4 && Input.GetKeyDown(KeyCode.A))                       // if player presses "A" when "rotationInt equals 4...
            {
                rotationInt = 3;                                                            // assign "rotationInt" a new number in the negative direction...
                GetComponent<SpriteRenderer>().sprite = red;                                // assign "red" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "red");                                     // and set the "colour" playerpref to "red" so the game scene knows which colour frog to use
            }

            if (rotationInt == 0 && Input.GetKeyDown(KeyCode.D))                            // if player presses "D" when "rotationInt equals 0...
            {
                rotationInt = 1;                                                            // assign "rotationInt" a new number in the positive direction...
                GetComponent<SpriteRenderer>().sprite = orange;                             // assign "orange" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "orange");                                  // and set the "colour" playerpref to "orange" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 1 && Input.GetKeyDown(KeyCode.D))                       // if player presses "D" when "rotationInt equals 1...
            {
                rotationInt = 2;                                                            // assign "rotationInt" a new number in the positive direction...
                GetComponent<SpriteRenderer>().sprite = purple;                             // assign "purple" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "purple");                                  // and set the "colour" playerpref to "purple" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 2 && Input.GetKeyDown(KeyCode.D))                       // if player presses "D" when "rotationInt equals 2...
            {
                rotationInt = 3;                                                            // assign "rotationInt" a new number in the positive direction...
                GetComponent<SpriteRenderer>().sprite = red;                                // assign "red" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "red");                                     // and set the "colour" playerpref to "red" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 3 && Input.GetKeyDown(KeyCode.D))                       // if player presses "D" when "rotationInt equals 3...
            {
                rotationInt = 4;                                                            // assign "rotationInt" a new number in the positive direction...
                GetComponent<SpriteRenderer>().sprite = white;                              // assign "white" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "white");                                   // and set the "colour" playerpref to "white" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 4 && Input.GetKeyDown(KeyCode.D))                       // if player presses "D" when "rotationInt equals 4...
            {
                rotationInt = 5;                                                            // assign "rotationInt" a new number in the positive direction...
                GetComponent<SpriteRenderer>().sprite = evil;                               // assign "evil" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "evil");                                    // and set the "colour" playerpref to "evil" so the game scene knows which colour frog to use
            }

            else if (rotationInt == 5 && Input.GetKeyDown(KeyCode.D))                       // if player presses "D" when "rotationInt equals 5...
            {
                rotationInt = 0;                                                            // assign "rotationInt" a new number in the positive direction...
                GetComponent<SpriteRenderer>().sprite = green;                              // assign "green" sprite to the sprite component of the gameobject...
                PlayerPrefs.SetString("colour", "green");                                   // and set the "colour" playerpref to "green" so the game scene knows which colour frog to use
            }
        }
    }
}
